#spring:
#  datasource:
#    username: root
#    password: Root@22031998#
#    url: jdbc:mysql://localhost:3306/bhupesh_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect